### PR TITLE
AsyncEnumerable Ambiguity Causes Build Errors on .NET 10 (v13.0)

### LINKED ISSUE #1397: AsyncEnumerable Ambiguity Causes Build Errors on .NET 10 (v13.0)
#### Description

While upgrading to .NET 10, the following libraries cause issues:
- `System.Linq.Async` - ambiguity for some methods, because of a [breaking change introduced by Microsoft](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/10.0/asyncenumerable)

#### Expected behavior

No ambiguity issues with .NET 10

#### Actual behavior

Compilation errors

#### Versions

- 12.0.4
- 13.0.3

### Steps to reproduce

- change the framework to .NET 10

### Relevant log output

```shell

```

#### Possible solutions
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/10.0/asyncenumerable#recommended-action

### PR DESCRIPTION
**Pull request by particularbot**
- Fixes #1397 

* Converted CI workflow `dotnet-version` to `global-json-file`
* Converted release workflow `dotnet-version` to `global-json-file`
* Set test project target frameworks (not including .NET Framework) to `net10.0`
* Update GitHub Actions versions:
    * `actions/checkout` to `v6.0.1`
    * `actions/setup-dotnet` to `v5.0.1`
    * `actions/upload-artifact` to `v6.0.0`
    * `azure/login` to `v2.3.0`
    * `Particular/push-octopus-package-action` to `v2.1.0`
    * `Particular/run-tests-action` to `v1.7.0`
    * `Particular/setup-azurestorage-action` to `v2.0.0`
    * `Particular/setup-cosmosdb-action` to `v1.5.3`
    * `Particular/sign-nuget-packages-action` to `v1.0.0`
* Updated .NET SDK in global.json to `10.0.100`

### CODE REVIEW

File: src/Tests/PubSub/SubscriptionStoreTests.cs [hunk 1]
```diff
@@ -50,14 +50,13 @@ public async Task Subscribe_should_create_topics()
                 .ConfigureAwait(false);
             var topics = entities.Select(x => x.PartitionKey).ToList();
 
-            CollectionAssert.AreEqual(new[]
-            {
+            Assert.That(topics, Is.EqualTo([
                 typeof(MyOtherEvent).FullName,
-                typeof(MyOtherUnrelatedEvent).FullName,
-            }, topics);
+                typeof(MyOtherUnrelatedEvent).FullName
```
Comment (mnadareski-particular) [inline src/Tests/PubSub/SubscriptionStoreTests.cs]: Do we prefer the hanging comma at the end of collections? I've seen it both ways, so just checking.
